# -*- coding: utf-8 -*-
"""pbl_bleu

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jAb4GgvMaPvCaJkB4pjOAC2YiXPSdj_Y
"""
# ライブラリのインストール

! pip install janome

# 単語分割

from janome.tokenizer import Tokenizer
tokenizer = Tokenizer()

# 実際に返ってきた応答文
fout = open("outou.txt", "w")
fin = open("/outou.txt", "r")
for line in fin:
    fout.write(" ".join([token.surface for token in tokenizer.tokenize(line.strip())]) + "\n")
fin.close()
fout.close()

# 自分たちが想定している応答文
fout = open("outou.test.txt", "w")
fin = open("/outou.test.txt", "r")
for line in fin:
    fout.write(" ".join([token.surface for token in tokenizer.tokenize(line.strip())]) + "\n")
fin.close()
fout.close()

# 評価

from torchtext.data.metrics import bleu_score

def bleu(fname_ref, fname_pred):    
    # 正解文
    fin = open(fname_ref, "r")
    refs = [[line.strip().split()] for line in fin]
    fin.close()
    # 出力文
    fin = open(fname_pred, "r")
    preds = [line.strip().split() for line in fin]
    fin.close()
    # BLEU
    score = bleu_score(preds, refs)
    print("BLEU = %.2f" % (score*100))

ref_file = "outou.test.txt"
pred_file = "outou.txt"
bleu(ref_file, pred_file)

